sudo: false
language: erlang
install: 'true'
script: ./rebar3 do update, eunit
otp_release:
   - 18.1
   - 17.5
   - 17.1
   - 17.0
   - R16B03-1
   - R16B03
   - R16B02
   - R16B01
   - R15B03
   - R15B02
